query GetFamilyAndFriendsData($userId: uuid!) {
  allUsers: users(orderBy: { name: ASC }) {
    id
    name
    photo
  }
  user: usersByPk(id: $userId) {
    follows(orderBy: { user: { name: ASC } }) {
      user {
        id
        name
        photo
        username
      }
    }
    claims {
      id
      giftIdea {
        userId
      }
    }
  }
}

mutation FollowUser($followingId: uuid!) {
  insertFollows(objects: { followingId: $followingId }) {
    returning {
      followerId
      followingId
    }
  }
}

mutation UnFollowUser($followerId: uuid!, $followingId: uuid!) {
  deleteFollowsByPk(followerId: $followerId, followingId: $followingId) {
    createdAt
  }
}
