mutation CreateGenericWishList {
  insertWishlistsOne(object: { title: "Wish list" }) {
    id
    title
  }
}

query GetWishlistByUserId($userId: uuid!) {
  wishlists(where: { createdById: { _eq: $userId } }) {
    id
    title
  }
}

query GetMyList($userId: uuid!) {
  wishlists(where: { createdById: { _eq: $userId } }) {
    id
    giftIdeas(where: { removed: { _neq: true } }, orderBy: { createdAt: ASC }) {
      id
      title
    }
  }
}

mutation InsertGiftIdea($input: GiftIdeasInsertInput!) {
  giftIdea: insertGiftIdeasOne(object: $input) {
    id
    title
  }
}

fragment MyListGiftIdeaFields on GiftIdeas {
  id
  title
  description
  url
  removed
  wishlistId
}

mutation UpdateGiftIdea($id: uuid!, $input: GiftIdeasSetInput!) {
  giftIdea: updateGiftIdeasByPk(pk_columns: { id: $id }, _set: $input) {
    ...MyListGiftIdeaFields
  }
}

query GetGiftIdeaById($id: uuid!) {
  giftIdea: giftIdeasByPk(id: $id) {
    ...MyListGiftIdeaFields
  }
}
